// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeganHelper.DAL.Data;

#nullable disable

namespace VeganHelper.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VeganHelper.DAL.Models.AiUsage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("FeatureType")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)")
                        .HasColumnName("feature_type");

                    b.Property<Guid?>("GuestSessionId")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("guest_session_id");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("INT")
                        .HasColumnName("input_tokens");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("model_name");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("INT")
                        .HasColumnName("output_tokens");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)")
                        .HasColumnName("provider");

                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("request_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'pending'");

                    b.Property<long?>("UserId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_ai_usage");

                    b.HasAlternateKey("RequestId")
                        .HasName("UQ_ai_usage_request_id");

                    b.HasIndex("GuestSessionId", "FeatureType", "CreatedAt")
                        .HasDatabaseName("IX_ai_usage_2");

                    b.HasIndex("UserId", "FeatureType", "CreatedAt")
                        .HasDatabaseName("IX_ai_usage_1");

                    b.ToTable("ai_usage", null, t =>
                        {
                            t.HasCheckConstraint("CK_ai_usage_1", "user_id IS NOT NULL OR guest_session_id IS NOT NULL");

                            t.HasCheckConstraint("CK_ai_usage_2", "feature_type IN ('chatbot','meal_planner','video_summary','embedding','chat_summary','content_moderation')");

                            t.HasCheckConstraint("CK_ai_usage_3", "status IN ('pending','completed','failed')");

                            t.HasCheckConstraint("CK_ai_usage_4", "input_tokens >= 0");

                            t.HasCheckConstraint("CK_ai_usage_5", "output_tokens >= 0");
                        });
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryType")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(20)")
                        .HasColumnName("category_type");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("name");

                    b.Property<string>("PostCategoryKind")
                        .HasColumnType("NVARCHAR(20)")
                        .HasColumnName("post_category_kind");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(120)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("PK_categories");

                    b.HasAlternateKey("Slug")
                        .HasName("UQ_categories_slug");

                    b.HasAlternateKey("CategoryType", "Name")
                        .HasName("UQ_categories_1");

                    b.ToTable("categories", null, t =>
                        {
                            t.HasCheckConstraint("CK_categories_1", "category_type IN ('post','shop')");

                            t.HasCheckConstraint("CK_categories_2", "(category_type = 'shop' AND post_category_kind IS NULL) OR (category_type = 'post' AND post_category_kind IS NOT NULL AND post_category_kind IN ('food','recipe','topic'))");
                        });
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.ChatMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("message_text");

                    b.Property<string>("SenderType")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(20)")
                        .HasColumnName("sender_type");

                    b.Property<long>("SessionId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("session_id");

                    b.HasKey("Id")
                        .HasName("PK_chat_messages");

                    b.HasIndex("SessionId", "Id")
                        .HasDatabaseName("IX_chat_messages_1");

                    b.ToTable("chat_messages", null, t =>
                        {
                            t.HasCheckConstraint("CK_chat_messages_1", "sender_type IN ('user','ai')");
                        });
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.ChatSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ContextSummary")
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("context_summary");

                    b.Property<Guid?>("GuestSessionId")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("guest_session_id");

                    b.Property<DateTime>("LastActivityAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("last_activity_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long?>("SummaryThroughMessageId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("summary_through_message_id");

                    b.Property<long?>("UserId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_chat_sessions");

                    b.HasIndex("GuestSessionId", "LastActivityAt")
                        .HasDatabaseName("IX_chat_sessions_2");

                    b.HasIndex("UserId", "LastActivityAt")
                        .HasDatabaseName("IX_chat_sessions_1");

                    b.ToTable("chat_sessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_chat_sessions_1", "user_id IS NOT NULL OR guest_session_id IS NOT NULL");

                            t.HasCheckConstraint("CK_chat_sessions_2", "(context_summary IS NULL AND summary_through_message_id IS NULL) OR (context_summary IS NOT NULL AND summary_through_message_id IS NOT NULL AND summary_through_message_id > 0)");
                        });
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.Comment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(1000)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<long?>("ParentCommentId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("parent_comment_id");

                    b.Property<long>("PostId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("post_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'visible'");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_comments");

                    b.HasAlternateKey("PostId", "Id")
                        .HasName("UQ_comments_1");

                    b.HasIndex("UserId");

                    b.HasIndex("PostId", "CreatedAt")
                        .HasDatabaseName("IX_comments_1");

                    b.HasIndex("PostId", "ParentCommentId");

                    b.ToTable("comments", null, t =>
                        {
                            t.HasCheckConstraint("CK_comments_1", "parent_comment_id IS NULL OR parent_comment_id <> id");

                            t.HasCheckConstraint("CK_comments_2", "status IN ('visible','hidden')");

                            t.HasCheckConstraint("CK_comments_3", "(is_deleted = 0 AND deleted_at IS NULL) OR (is_deleted = 1 AND deleted_at IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.Flag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AiModelName")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("ai_model_name");

                    b.Property<long?>("CommentId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("comment_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long?>("PostId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("post_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("reason");

                    b.Property<long?>("ReporterId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("reporter_id");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("NVARCHAR(2000)")
                        .HasColumnName("resolution_note");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("resolved_at");

                    b.Property<long?>("ResolvedByAdminId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("resolved_by_admin_id");

                    b.Property<long?>("ShopId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("shop_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(10)")
                        .HasColumnName("source_type")
                        .HasDefaultValueSql("'user'");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'pending'");

                    b.HasKey("Id")
                        .HasName("PK_flags");

                    b.HasIndex("CommentId");

                    b.HasIndex("PostId");

                    b.HasIndex("ReporterId");

                    b.HasIndex("ResolvedByAdminId");

                    b.HasIndex("ShopId");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_flags_1");

                    b.ToTable("flags", null, t =>
                        {
                            t.HasCheckConstraint("CK_flags_1", "status IN ('pending','resolved','dismissed')");

                            t.HasCheckConstraint("CK_flags_2", "(CASE WHEN post_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN comment_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN shop_id IS NOT NULL THEN 1 ELSE 0 END) = 1");

                            t.HasCheckConstraint("CK_flags_3", "(status = 'pending' AND resolved_by_admin_id IS NULL AND resolved_at IS NULL) OR (status IN ('resolved','dismissed') AND resolved_by_admin_id IS NOT NULL AND resolved_at IS NOT NULL)");

                            t.HasCheckConstraint("CK_flags_4", "(source_type = 'user' AND reporter_id IS NOT NULL AND ai_model_name IS NULL) OR (source_type = 'ai' AND reporter_id IS NULL AND ai_model_name IS NOT NULL AND post_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.Ingredient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("CaloriesPer100g")
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("calories_per_100g");

                    b.Property<string>("DefaultUnit")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(20)")
                        .HasColumnName("default_unit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK_ingredients");

                    b.HasAlternateKey("Name")
                        .HasName("UQ_ingredients_name");

                    b.ToTable("ingredients", null, t =>
                        {
                            t.HasCheckConstraint("CK_ingredients_1", "calories_per_100g >= 0");
                        });
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.Meal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ComboName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("combo_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("description");

                    b.Property<string>("DietType")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)")
                        .HasColumnName("diet_type");

                    b.Property<long?>("OwnerUserId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("owner_user_id");

                    b.Property<decimal>("Servings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("servings")
                        .HasDefaultValueSql("1");

                    b.Property<decimal?>("TotalCalories")
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("total_calories");

                    b.HasKey("Id")
                        .HasName("PK_meals");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("meals", null, t =>
                        {
                            t.HasCheckConstraint("CK_meals_1", "servings > 0");

                            t.HasCheckConstraint("CK_meals_2", "total_calories >= 0");

                            t.HasCheckConstraint("CK_meals_3", "diet_type IN ('vegan','lacto_ovo_vegetarian')");
                        });
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.MealIngredient", b =>
                {
                    b.Property<long>("MealId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("meal_id");

                    b.Property<long>("IngredientId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("ingredient_id");

                    b.Property<decimal?>("CalculatedQuantity")
                        .HasColumnType("DECIMAL(12,3)")
                        .HasColumnName("calculated_quantity");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(20)")
                        .HasColumnName("unit");

                    b.HasKey("MealId", "IngredientId")
                        .HasName("PK_meal_ingredients");

                    b.HasIndex("IngredientId");

                    b.ToTable("meal_ingredients", null, t =>
                        {
                            t.HasCheckConstraint("CK_meal_ingredients_1", "calculated_quantity > 0");
                        });
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.MealPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AllergiesSnapshot")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("allergies_snapshot")
                        .HasDefaultValueSql("N'[]'");

                    b.Property<string>("AvailableIngredientsSnapshot")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("available_ingredients_snapshot")
                        .HasDefaultValueSql("N'[]'");

                    b.Property<decimal>("BmiValue")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("bmi_value");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("DietType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(30)")
                        .HasColumnName("diet_type")
                        .HasDefaultValueSql("'vegan'");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("DATE")
                        .HasColumnName("end_date");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("NVARCHAR(2000)")
                        .HasColumnName("error_message");

                    b.Property<string>("GenerationSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(20)")
                        .HasColumnName("generation_source")
                        .HasDefaultValueSql("'ai'");

                    b.Property<decimal>("HeightCm")
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("height_cm");

                    b.Property<string>("ModelName")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("model_name");

                    b.Property<DateTime?>("SavedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("saved_at");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("DATE")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'pending'");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("user_id");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id")
                        .HasName("PK_meal_plans");

                    b.HasIndex("UserId", "StartDate")
                        .HasDatabaseName("IX_meal_plans_1");

                    b.ToTable("meal_plans", null, t =>
                        {
                            t.HasCheckConstraint("CK_meal_plans_1", "DATEDIFF(DAY, start_date, end_date) = 6");

                            t.HasCheckConstraint("CK_meal_plans_2", "height_cm > 0 AND weight_kg > 0 AND bmi_value > 0");

                            t.HasCheckConstraint("CK_meal_plans_3", "diet_type IN ('vegan','lacto_ovo_vegetarian')");

                            t.HasCheckConstraint("CK_meal_plans_4", "ISJSON(allergies_snapshot) = 1");

                            t.HasCheckConstraint("CK_meal_plans_5", "ISJSON(available_ingredients_snapshot) = 1");

                            t.HasCheckConstraint("CK_meal_plans_6", "generation_source IN ('ai','manual')");

                            t.HasCheckConstraint("CK_meal_plans_7", "status IN ('pending','generating','completed','failed','saved','archived')");
                        });
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.MealPlanSchedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte>("DayOfWeek")
                        .HasColumnType("TINYINT")
                        .HasColumnName("day_of_week");

                    b.Property<long>("MealId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("meal_id");

                    b.Property<long>("MealPlanId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("meal_plan_id");

                    b.Property<string>("MealTime")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(20)")
                        .HasColumnName("meal_time");

                    b.Property<decimal>("PortionMultiplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("portion_multiplier")
                        .HasDefaultValueSql("1");

                    b.HasKey("Id")
                        .HasName("PK_meal_plan_schedule");

                    b.HasAlternateKey("MealPlanId", "DayOfWeek", "MealTime")
                        .HasName("UQ_meal_plan_schedule_1");

                    b.HasIndex("MealId");

                    b.ToTable("meal_plan_schedule", null, t =>
                        {
                            t.HasCheckConstraint("CK_meal_plan_schedule_1", "day_of_week BETWEEN 1 AND 7");

                            t.HasCheckConstraint("CK_meal_plan_schedule_2", "meal_time IN ('breakfast','lunch','dinner')");

                            t.HasCheckConstraint("CK_meal_plan_schedule_3", "portion_multiplier > 0");
                        });
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.Post", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AuthorId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("author_id");

                    b.Property<decimal?>("CaloriesPerServing")
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("calories_per_serving");

                    b.Property<string>("Content")
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("content");

                    b.Property<int?>("CookingTimeMins")
                        .HasColumnType("INT")
                        .HasColumnName("cooking_time_mins");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DietType")
                        .HasColumnType("NVARCHAR(30)")
                        .HasColumnName("diet_type");

                    b.Property<bool>("IngredientsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(false)
                        .HasColumnName("ingredients_verified");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("MealType")
                        .HasColumnType("NVARCHAR(20)")
                        .HasColumnName("meal_type");

                    b.Property<string>("PostType")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(20)")
                        .HasColumnName("post_type");

                    b.Property<int?>("PrepTimeMins")
                        .HasColumnType("INT")
                        .HasColumnName("prep_time_mins");

                    b.Property<int?>("Servings")
                        .HasColumnType("INT")
                        .HasColumnName("servings");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'draft'");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("updated_at");

                    b.Property<long>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasColumnName("view_count")
                        .HasDefaultValueSql("0");

                    b.HasKey("Id")
                        .HasName("PK_posts");

                    b.HasIndex("AuthorId", "CreatedAt")
                        .HasDatabaseName("IX_posts_2");

                    b.HasIndex("Status", "IsDeleted", "CreatedAt")
                        .HasDatabaseName("IX_posts_1");

                    b.ToTable("posts", null, t =>
                        {
                            t.HasCheckConstraint("CK_posts_1", "post_type IN ('article','video','recipe','community')");

                            t.HasCheckConstraint("CK_posts_10", "(is_deleted = 0 AND deleted_at IS NULL) OR (is_deleted = 1 AND deleted_at IS NOT NULL)");

                            t.HasCheckConstraint("CK_posts_2", "meal_type IN ('breakfast','lunch','dinner','snack')");

                            t.HasCheckConstraint("CK_posts_3", "diet_type IN ('vegan','lacto_ovo_vegetarian')");

                            t.HasCheckConstraint("CK_posts_4", "status IN ('draft','pending_review','published','rejected','hidden')");

                            t.HasCheckConstraint("CK_posts_5", "prep_time_mins >= 0");

                            t.HasCheckConstraint("CK_posts_6", "cooking_time_mins >= 0");

                            t.HasCheckConstraint("CK_posts_7", "servings > 0");

                            t.HasCheckConstraint("CK_posts_8", "calories_per_serving >= 0");

                            t.HasCheckConstraint("CK_posts_9", "view_count >= 0");
                        });
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.PostCategory", b =>
                {
                    b.Property<long>("PostId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("post_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INT")
                        .HasColumnName("category_id");

                    b.HasKey("PostId", "CategoryId")
                        .HasName("PK_post_categories");

                    b.HasIndex("CategoryId");

                    b.ToTable("post_categories", (string)null);
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.PostEmbedding", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("INT")
                        .HasColumnName("chunk_index");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTime?>("EmbeddedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("embedded_at");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("embedding_model");

                    b.Property<long>("PostId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("post_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'pending'");

                    b.Property<string>("VectorId")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("vector_id");

                    b.HasKey("Id")
                        .HasName("PK_post_embeddings");

                    b.HasAlternateKey("PostId", "ChunkIndex")
                        .HasName("UQ_post_embeddings_1");

                    b.HasIndex("Status", "PostId")
                        .HasDatabaseName("IX_post_embeddings_1");

                    b.ToTable("post_embeddings", null, t =>
                        {
                            t.HasCheckConstraint("CK_post_embeddings_1", "chunk_index >= 0");

                            t.HasCheckConstraint("CK_post_embeddings_2", "status IN ('pending','processing','completed','failed','stale')");

                            t.HasCheckConstraint("CK_post_embeddings_3", "status <> 'completed' OR (vector_id IS NOT NULL AND embedded_at IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.PostIngredient", b =>
                {
                    b.Property<long>("PostId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("post_id");

                    b.Property<long>("IngredientId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("ingredient_id");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("DECIMAL(12,3)")
                        .HasColumnName("quantity");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(20)")
                        .HasColumnName("unit");

                    b.HasKey("PostId", "IngredientId")
                        .HasName("PK_post_ingredients");

                    b.HasIndex("IngredientId");

                    b.ToTable("post_ingredients", null, t =>
                        {
                            t.HasCheckConstraint("CK_post_ingredients_1", "quantity > 0");
                        });
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.PostLike", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("user_id");

                    b.Property<long>("PostId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("post_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("UserId", "PostId")
                        .HasName("PK_post_likes");

                    b.HasIndex("PostId");

                    b.ToTable("post_likes", (string)null);
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.PostMedia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CloudPublicId")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("cloud_public_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("display_order")
                        .HasDefaultValueSql("0");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INT")
                        .HasColumnName("duration_seconds");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(20)")
                        .HasColumnName("media_type");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(1000)")
                        .HasColumnName("media_url");

                    b.Property<long>("PostId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("post_id");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(20)")
                        .HasColumnName("processing_status")
                        .HasDefaultValueSql("'ready'");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("NVARCHAR(1000)")
                        .HasColumnName("thumbnail_url");

                    b.HasKey("Id")
                        .HasName("PK_post_media");

                    b.HasAlternateKey("PostId", "Id")
                        .HasName("UQ_post_media_1");

                    b.HasIndex("PostId")
                        .IsUnique()
                        .HasDatabaseName("IX_post_media_1")
                        .HasFilter("is_primary = 1");

                    b.ToTable("post_media", null, t =>
                        {
                            t.HasCheckConstraint("CK_post_media_1", "media_type IN ('image','video')");

                            t.HasCheckConstraint("CK_post_media_2", "processing_status IN ('uploading','processing','ready','failed')");

                            t.HasCheckConstraint("CK_post_media_3", "duration_seconds >= 0");

                            t.HasCheckConstraint("CK_post_media_4", "display_order >= 0");
                        });
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.PostSummary", b =>
                {
                    b.Property<long>("PostId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("post_id");

                    b.Property<string>("AiGeneratedText")
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("ai_generated_text");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("NVARCHAR(2000)")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("GeneratedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("generated_at");

                    b.Property<string>("ModelName")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("model_name");

                    b.Property<DateTime>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("requested_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long>("SourceMediaId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("source_media_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'pending'");

                    b.Property<string>("Transcript")
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("transcript");

                    b.HasKey("PostId")
                        .HasName("PK_post_summaries");

                    b.HasIndex("PostId", "SourceMediaId");

                    b.ToTable("post_summaries", null, t =>
                        {
                            t.HasCheckConstraint("CK_post_summaries_1", "status IN ('pending','processing','completed','failed','stale')");

                            t.HasCheckConstraint("CK_post_summaries_2", "status <> 'completed' OR (transcript IS NOT NULL AND ai_generated_text IS NOT NULL AND generated_at IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)")
                        .HasColumnName("role_name");

                    b.HasKey("Id")
                        .HasName("PK_roles");

                    b.HasAlternateKey("RoleName")
                        .HasName("UQ_roles_role_name");

                    b.ToTable("roles", null, t =>
                        {
                            t.HasCheckConstraint("CK_roles_1", "role_name IN ('member','admin')");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "member"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "admin"
                        });
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.SavedPost", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("user_id");

                    b.Property<long>("PostId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("post_id");

                    b.Property<DateTime>("SavedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("saved_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("UserId", "PostId")
                        .HasName("PK_saved_posts");

                    b.HasIndex("PostId");

                    b.ToTable("saved_posts", (string)null);
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.Shop", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("NVARCHAR(1000)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("GooglePlaceId")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("google_place_id");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(false)
                        .HasColumnName("is_approved");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("DECIMAL(10,7)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("DECIMAL(10,7)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("name");

                    b.Property<long?>("SuggestedByUserId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("suggested_by_user_id");

                    b.HasKey("Id")
                        .HasName("PK_shops");

                    b.HasIndex("GooglePlaceId")
                        .IsUnique()
                        .HasDatabaseName("IX_shops_1")
                        .HasFilter("google_place_id IS NOT NULL");

                    b.HasIndex("SuggestedByUserId");

                    b.ToTable("shops", null, t =>
                        {
                            t.HasCheckConstraint("CK_shops_1", "latitude BETWEEN -90 AND 90");

                            t.HasCheckConstraint("CK_shops_2", "longitude BETWEEN -180 AND 180");

                            t.HasCheckConstraint("CK_shops_3", "(latitude IS NULL AND longitude IS NULL) OR (latitude IS NOT NULL AND longitude IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.ShopCategory", b =>
                {
                    b.Property<long>("ShopId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("shop_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INT")
                        .HasColumnName("category_id");

                    b.HasKey("ShopId", "CategoryId")
                        .HasName("PK_shop_categories");

                    b.HasIndex("CategoryId");

                    b.ToTable("shop_categories", (string)null);
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("email_verified_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("password_hash");

                    b.Property<int>("RoleId")
                        .HasColumnType("INT")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("PK_users");

                    b.HasAlternateKey("Email")
                        .HasName("UQ_users_email");

                    b.HasAlternateKey("Username")
                        .HasName("UQ_users_username");

                    b.HasIndex("RoleId");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("CK_users_1", "deleted_at IS NULL OR is_active = 0");
                        });
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.UserAllergy", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("user_id");

                    b.Property<long>("IngredientId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("ingredient_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("UserId", "IngredientId")
                        .HasName("PK_user_allergies");

                    b.HasIndex("IngredientId");

                    b.ToTable("user_allergies", (string)null);
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.UserAvailableIngredient", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("user_id");

                    b.Property<long>("IngredientId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("ingredient_id");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("DECIMAL(12,3)")
                        .HasColumnName("quantity");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(20)")
                        .HasColumnName("unit");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("UserId", "IngredientId")
                        .HasName("PK_user_available_ingredients");

                    b.HasIndex("IngredientId");

                    b.ToTable("user_available_ingredients", null, t =>
                        {
                            t.HasCheckConstraint("CK_user_available_ingredients_1", "quantity >= 0");
                        });
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.UserIdentity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(20)")
                        .HasColumnName("provider")
                        .HasDefaultValueSql("'google'");

                    b.Property<string>("ProviderSubject")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("provider_subject");

                    b.Property<long>("UserId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_user_identities");

                    b.HasAlternateKey("Provider", "ProviderSubject")
                        .HasName("UQ_user_identities_1");

                    b.HasIndex("UserId");

                    b.ToTable("user_identities", null, t =>
                        {
                            t.HasCheckConstraint("CK_user_identities_1", "provider IN ('google')");
                        });
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.UserProfile", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("user_id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("NVARCHAR(1000)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("BiologicalSex")
                        .HasColumnType("NVARCHAR(20)")
                        .HasColumnName("biological_sex");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("DATE")
                        .HasColumnName("birth_date");

                    b.Property<string>("DietType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(30)")
                        .HasColumnName("diet_type")
                        .HasDefaultValueSql("'vegan'");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("display_name");

                    b.Property<decimal?>("HeightCm")
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("height_cm");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("UserId")
                        .HasName("PK_user_profiles");

                    b.ToTable("user_profiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_user_profiles_1", "height_cm IS NULL OR height_cm > 0");

                            t.HasCheckConstraint("CK_user_profiles_2", "weight_kg IS NULL OR weight_kg > 0");

                            t.HasCheckConstraint("CK_user_profiles_3", "biological_sex IN ('male','female','other')");

                            t.HasCheckConstraint("CK_user_profiles_4", "diet_type IN ('vegan','lacto_ovo_vegetarian')");
                        });
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.AiUsage", b =>
                {
                    b.HasOne("VeganHelper.DAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_ai_usage_1");
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.ChatMessage", b =>
                {
                    b.HasOne("VeganHelper.DAL.Models.ChatSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_chat_messages_1");
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.ChatSession", b =>
                {
                    b.HasOne("VeganHelper.DAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_chat_sessions_1");
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.Comment", b =>
                {
                    b.HasOne("VeganHelper.DAL.Models.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_comments_1");

                    b.HasOne("VeganHelper.DAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_comments_2");

                    b.HasOne("VeganHelper.DAL.Models.Comment", null)
                        .WithMany()
                        .HasForeignKey("PostId", "ParentCommentId")
                        .HasPrincipalKey("PostId", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_comments_3");
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.Flag", b =>
                {
                    b.HasOne("VeganHelper.DAL.Models.Comment", null)
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_flags_3");

                    b.HasOne("VeganHelper.DAL.Models.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_flags_2");

                    b.HasOne("VeganHelper.DAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_flags_1");

                    b.HasOne("VeganHelper.DAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ResolvedByAdminId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_flags_5");

                    b.HasOne("VeganHelper.DAL.Models.Shop", null)
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_flags_4");
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.Meal", b =>
                {
                    b.HasOne("VeganHelper.DAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_meals_1");
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.MealIngredient", b =>
                {
                    b.HasOne("VeganHelper.DAL.Models.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_meal_ingredients_2");

                    b.HasOne("VeganHelper.DAL.Models.Meal", null)
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_meal_ingredients_1");
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.MealPlan", b =>
                {
                    b.HasOne("VeganHelper.DAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_meal_plans_1");
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.MealPlanSchedule", b =>
                {
                    b.HasOne("VeganHelper.DAL.Models.Meal", null)
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_meal_plan_schedule_2");

                    b.HasOne("VeganHelper.DAL.Models.MealPlan", null)
                        .WithMany()
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_meal_plan_schedule_1");
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.Post", b =>
                {
                    b.HasOne("VeganHelper.DAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_posts_1");
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.PostCategory", b =>
                {
                    b.HasOne("VeganHelper.DAL.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_post_categories_2");

                    b.HasOne("VeganHelper.DAL.Models.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_post_categories_1");
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.PostEmbedding", b =>
                {
                    b.HasOne("VeganHelper.DAL.Models.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_post_embeddings_1");
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.PostIngredient", b =>
                {
                    b.HasOne("VeganHelper.DAL.Models.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_post_ingredients_2");

                    b.HasOne("VeganHelper.DAL.Models.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_post_ingredients_1");
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.PostLike", b =>
                {
                    b.HasOne("VeganHelper.DAL.Models.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_post_likes_2");

                    b.HasOne("VeganHelper.DAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_post_likes_1");
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.PostMedia", b =>
                {
                    b.HasOne("VeganHelper.DAL.Models.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_post_media_1");
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.PostSummary", b =>
                {
                    b.HasOne("VeganHelper.DAL.Models.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_post_summaries_1");

                    b.HasOne("VeganHelper.DAL.Models.PostMedia", null)
                        .WithMany()
                        .HasForeignKey("PostId", "SourceMediaId")
                        .HasPrincipalKey("PostId", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_post_summaries_2");
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.SavedPost", b =>
                {
                    b.HasOne("VeganHelper.DAL.Models.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_saved_posts_2");

                    b.HasOne("VeganHelper.DAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_saved_posts_1");
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.Shop", b =>
                {
                    b.HasOne("VeganHelper.DAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("SuggestedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_shops_1");
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.ShopCategory", b =>
                {
                    b.HasOne("VeganHelper.DAL.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_shop_categories_2");

                    b.HasOne("VeganHelper.DAL.Models.Shop", null)
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_shop_categories_1");
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.User", b =>
                {
                    b.HasOne("VeganHelper.DAL.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_users_1");
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.UserAllergy", b =>
                {
                    b.HasOne("VeganHelper.DAL.Models.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_user_allergies_2");

                    b.HasOne("VeganHelper.DAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_user_allergies_1");
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.UserAvailableIngredient", b =>
                {
                    b.HasOne("VeganHelper.DAL.Models.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_user_available_ingredients_2");

                    b.HasOne("VeganHelper.DAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_user_available_ingredients_1");
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.UserIdentity", b =>
                {
                    b.HasOne("VeganHelper.DAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_user_identities_1");
                });

            modelBuilder.Entity("VeganHelper.DAL.Models.UserProfile", b =>
                {
                    b.HasOne("VeganHelper.DAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_user_profiles_1");
                });
#pragma warning restore 612, 618
        }
    }
}
