<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <UserSecretsId>VeganHelper-API-Development</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../VeganHelper.BLL/VeganHelper.BLL.csproj" />
    <ProjectReference Include="../VeganHelper.DAL/VeganHelper.DAL.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>
</Project>
